"""empty message

Revision ID: 22cbe827aa20
Revises: 
Create Date: 2025-05-27 18:07:47.328016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22cbe827aa20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_column('ip_origen')

    with op.batch_alter_table('avance', schema=None) as batch_op:
        batch_op.alter_column('meta_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secretaria_id', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'entidad_responsable', ['secretaria_id'], ['entidad_id'], onupdate='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('secretaria_id')

    with op.batch_alter_table('avance', schema=None) as batch_op:
        batch_op.alter_column('meta_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_origen', mysql.VARCHAR(length=45), nullable=True))

    # ### end Alembic commands ###
