"""Fix MetaIndicador-Usuario relationship

Revision ID: 664312f2951e
Revises: 79cb97c3de3e
Create Date: 2025-05-27 11:41:57.467636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '664312f2951e'
down_revision = '79cb97c3de3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Entidad_Responsable',
    sa.Column('entidad_id', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_entidad', sa.Enum('LIDER', 'CORRESPONSABLE', name='tipoentidad'), nullable=False),
    sa.PrimaryKeyConstraint('entidad_id')
    )
    op.create_table('Indicador',
    sa.Column('indicador_id', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('unidad_medida', sa.String(length=20), nullable=True),
    sa.Column('frecuencia_calculo', sa.Enum('DIARIO', 'SEMANAL', 'MENSUAL', 'TRIMESTRAL', 'SEMESTRAL', 'ANUAL', 'PERSONALIZADO', name='frecuenciacalculo'), nullable=True),
    sa.Column('es_critico', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('indicador_id')
    )
    op.create_table('Meta',
    sa.Column('meta_id', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('meta_resultado', sa.Text(), nullable=True),
    sa.Column('descripcion_resultado', sa.Text(), nullable=True),
    sa.Column('unidad_medida', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.Enum('PLANIFICADA', 'EN_EJECUCION', 'CUMPLIDA', 'CANCELADA', name='estadometaenum'), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('fecha_registro', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('meta_id')
    )
    op.create_table('Permiso',
    sa.Column('permiso_id', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('nivel_acceso', sa.Enum('LECTURA', 'ESCRITURA', 'TOTAL', name='nivelacceso'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('permiso_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('Rol',
    sa.Column('rol_id', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('rol_id')
    )
    op.create_table('Meta_Entidad',
    sa.Column('meta_id', sa.String(length=20), nullable=False),
    sa.Column('entidad_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['entidad_id'], ['Entidad_Responsable.entidad_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meta_id'], ['Meta.meta_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meta_id', 'entidad_id')
    )
    op.create_table('Rol_Permiso',
    sa.Column('rol_id', sa.String(length=20), nullable=False),
    sa.Column('permiso_id', sa.String(length=20), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['permiso_id'], ['Permiso.permiso_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['Rol.rol_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('Usuario',
    sa.Column('usuario_id', sa.String(length=20), nullable=False),
    sa.Column('rol_id', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('intentos_fallidos', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('fecha_bloqueo', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['Rol.rol_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Auditoria',
    sa.Column('auditoria_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.String(length=20), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('entidad_afectada', sa.String(length=50), nullable=False),
    sa.Column('id_entidad', sa.String(length=50), nullable=True),
    sa.Column('fecha_accion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('detalles', sa.JSON(), nullable=True),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('resultado', sa.Enum('EXITO', 'FALLO', 'ADVERTENCIA', name='resultadoaccion'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('auditoria_id')
    )
    op.create_table('Avance',
    sa.Column('avance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meta_id', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.String(length=20), nullable=False),
    sa.Column('usuario_aprobador', sa.String(length=20), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.CheckConstraint('porcentaje >= 0 AND porcentaje <= 100', name='check_porcentaje_range'),
    sa.ForeignKeyConstraint(['meta_id'], ['Meta.meta_id'], ),
    sa.ForeignKeyConstraint(['usuario_aprobador'], ['Usuario.usuario_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('avance_id')
    )
    op.create_table('Documento',
    sa.Column('documento_id', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('PDF', 'DOCX', 'XLSX', 'PPTX', 'JPG', 'PNG', 'TXT', 'OTRO', name='tipodocumento'), nullable=False),
    sa.Column('tamaño_mb', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('ubicacion_almacenamiento', sa.String(length=512), nullable=True),
    sa.Column('hash_archivo', sa.String(length=64), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=True),
    sa.CheckConstraint('tamaño_mb > 0', name='check_tamaño_mb_positive'),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('documento_id')
    )
    op.create_table('Meta_Indicador',
    sa.Column('meta_id', sa.String(length=20), nullable=False),
    sa.Column('indicador_id', sa.String(length=20), nullable=False),
    sa.Column('valor_actual', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('meta', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fecha_calculo', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('calculado_por', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['calculado_por'], ['Usuario.usuario_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['indicador_id'], ['Indicador.indicador_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meta_id'], ['Meta.meta_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meta_id', 'indicador_id')
    )
    op.create_table('Notificacion',
    sa.Column('notificacion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.Enum('SISTEMA', 'DOCUMENTO', 'USUARIO', 'TAREA', 'REPORTE', 'ALERTA', 'INFORMATIVA', 'RECORDATORIO', 'APROBACION', name='tiponotificacion'), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fecha_lectura', sa.DateTime(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('url_accion', sa.String(length=512), nullable=True),
    sa.Column('prioridad', sa.Enum('BAJA', 'MEDIA', 'ALTA', 'URGENTE', 'CRITICA', name='prioridadnotificacion'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notificacion_id')
    )
    op.create_table('Reporte',
    sa.Column('reporte_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('parametros', mysql.JSON(), nullable=True),
    sa.Column('ubicacion_almacenamiento', sa.String(length=512), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PROCESANDO', 'COMPLETADO', 'FALLIDO', name='estadoreporte'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('reporte_id')
    )
    op.create_table('Version_Documento',
    sa.Column('version_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('documento_id', sa.String(length=20), nullable=False),
    sa.Column('numero_version', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.String(length=20), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('cambios', sa.Text(), nullable=True),
    sa.Column('hash_version', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['Documento.documento_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('documento_id', 'numero_version', name='uk_documento_version')
    )
    op.drop_table('entidad_responsable')
    op.drop_table('meta')
    op.drop_table('notificacion')
    with op.batch_alter_table('version_documento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uk_documento_version'))

    op.drop_table('version_documento')
    op.drop_table('auditoria')
    op.drop_table('rol')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('usuario')
    op.drop_table('indicador')
    op.drop_table('rol_permiso')
    op.drop_table('documento')
    op.drop_table('avance')
    with op.batch_alter_table('permiso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('nombre'))

    op.drop_table('permiso')
    op.drop_table('meta_entidad')
    op.drop_table('reporte')
    op.drop_table('meta_indicador')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_indicador',
    sa.Column('meta_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('indicador_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('valor_actual', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('meta', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('fecha_calculo', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('calculado_por', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['calculado_por'], ['usuario.usuario_id'], name=op.f('meta_indicador_ibfk_3'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['indicador_id'], ['indicador.indicador_id'], name=op.f('meta_indicador_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meta_id'], ['meta.meta_id'], name=op.f('meta_indicador_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meta_id', 'indicador_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reporte',
    sa.Column('reporte_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('fecha_generacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('fecha_inicio', sa.DATE(), nullable=True),
    sa.Column('fecha_fin', sa.DATE(), nullable=True),
    sa.Column('parametros', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('ubicacion_almacenamiento', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('estado', mysql.ENUM('PENDIENTE', 'PROCESANDO', 'COMPLETADO', 'FALLIDO'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], name=op.f('reporte_ibfk_1')),
    sa.PrimaryKeyConstraint('reporte_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('meta_entidad',
    sa.Column('meta_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('entidad_id', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidad_responsable.entidad_id'], name=op.f('meta_entidad_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meta_id'], ['meta.meta_id'], name=op.f('meta_entidad_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meta_id', 'entidad_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('permiso',
    sa.Column('permiso_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('nivel_acceso', mysql.ENUM('LECTURA', 'ESCRITURA', 'TOTAL'), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('permiso_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('permiso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('nombre'), ['nombre'], unique=True)

    op.create_table('avance',
    sa.Column('avance_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('meta_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=False),
    sa.Column('fecha_registro', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('porcentaje', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('aprobado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('usuario_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('usuario_aprobador', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('fecha_aprobacion', mysql.DATETIME(), nullable=True),
    sa.CheckConstraint('`porcentaje` >= 0 and `porcentaje` <= 100', name=op.f('check_porcentaje_range')),
    sa.ForeignKeyConstraint(['meta_id'], ['meta.meta_id'], name=op.f('avance_ibfk_1')),
    sa.ForeignKeyConstraint(['meta_id'], ['meta.meta_id'], name=op.f('fk_avance_meta_id')),
    sa.ForeignKeyConstraint(['usuario_aprobador'], ['usuario.usuario_id'], name=op.f('avance_ibfk_3'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], name=op.f('avance_ibfk_2')),
    sa.PrimaryKeyConstraint('avance_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('documento',
    sa.Column('documento_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('usuario_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('tipo', mysql.ENUM('PDF', 'DOCX', 'XLSX', 'PPTX', 'JPG', 'PNG', 'TXT', 'OTRO'), nullable=False),
    sa.Column('tamaño_mb', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fecha_subida', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('ubicacion_almacenamiento', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('hash_archivo', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('eliminado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('`tamaño_mb` > 0', name='check_tamaño_mb_positive'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], name='documento_ibfk_1'),
    sa.PrimaryKeyConstraint('documento_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rol_permiso',
    sa.Column('rol_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('permiso_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('fecha_asignacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.permiso_id'], name=op.f('rol_permiso_ibfk_2'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.rol_id'], name=op.f('rol_permiso_ibfk_1'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('indicador',
    sa.Column('indicador_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('formula', mysql.TEXT(), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('unidad_medida', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('frecuencia_calculo', mysql.ENUM('DIARIO', 'SEMANAL', 'MENSUAL', 'TRIMESTRAL', 'SEMESTRAL', 'ANUAL', 'PERSONALIZADO'), nullable=True),
    sa.Column('es_critico', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('indicador_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usuario',
    sa.Column('usuario_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('rol_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('ultimo_login', mysql.DATETIME(), nullable=True),
    sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('intentos_fallidos', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('fecha_bloqueo', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.rol_id'], name='usuario_ibfk_1', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('rol',
    sa.Column('rol_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('fecha_actualizacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('rol_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auditoria',
    sa.Column('auditoria_id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('accion', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('entidad_afectada', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('id_entidad', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_accion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('detalles', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('ip_origen', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('resultado', mysql.ENUM('EXITO', 'FALLO', 'ADVERTENCIA'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], name=op.f('auditoria_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('auditoria_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('version_documento',
    sa.Column('version_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('documento_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('numero_version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('usuario_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('fecha_modificacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('cambios', mysql.TEXT(), nullable=True),
    sa.Column('hash_version', mysql.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.documento_id'], name=op.f('version_documento_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], name=op.f('version_documento_ibfk_2')),
    sa.PrimaryKeyConstraint('version_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('version_documento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uk_documento_version'), ['documento_id', 'numero_version'], unique=True)

    op.create_table('notificacion',
    sa.Column('notificacion_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('tipo', mysql.ENUM('SISTEMA', 'DOCUMENTO', 'USUARIO', 'TAREA', 'REPORTE', 'ALERTA', 'INFORMATIVA', 'RECORDATORIO', 'APROBACION'), nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('mensaje', mysql.TEXT(), nullable=False),
    sa.Column('fecha_envio', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('fecha_lectura', mysql.DATETIME(), nullable=True),
    sa.Column('leida', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('url_accion', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('prioridad', mysql.ENUM('BAJA', 'MEDIA', 'ALTA', 'URGENTE', 'CRITICA'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], name=op.f('notificacion_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notificacion_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('meta',
    sa.Column('meta_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('meta_resultado', mysql.TEXT(), nullable=True),
    sa.Column('descripcion_resultado', mysql.TEXT(), nullable=True),
    sa.Column('unidad_medida', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('estado', mysql.ENUM('PLANIFICADA', 'EN_EJECUCION', 'CUMPLIDA', 'CANCELADA'), nullable=False),
    sa.Column('fecha_inicio', sa.DATE(), nullable=True),
    sa.Column('fecha_fin', sa.DATE(), nullable=True),
    sa.Column('fecha_registro', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('meta_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('entidad_responsable',
    sa.Column('entidad_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('tipo_entidad', mysql.ENUM('LIDER', 'CORRESPONSABLE'), nullable=False),
    sa.PrimaryKeyConstraint('entidad_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Version_Documento')
    op.drop_table('Reporte')
    op.drop_table('Notificacion')
    op.drop_table('Meta_Indicador')
    op.drop_table('Documento')
    op.drop_table('Avance')
    op.drop_table('Auditoria')
    op.drop_table('Usuario')
    op.drop_table('Rol_Permiso')
    op.drop_table('Meta_Entidad')
    op.drop_table('Rol')
    op.drop_table('Permiso')
    op.drop_table('Meta')
    op.drop_table('Indicador')
    op.drop_table('Entidad_Responsable')
    # ### end Alembic commands ###
