"""Actualizar definiciones ENUM para EstadoMetaEnum y ResultadoAccion

Revision ID: 835d943cece7
Revises: 70edb2aa9fc7
Create Date: 2025-05-28 14:40:43.213204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '835d943cece7'
down_revision = '70edb2aa9fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('PLANIFICADA', 'EN_EJECUCION', 'CUMPLIDA', 'CANCELADA'),
               type_=sa.Enum('PLANIFICADA', 'PENDIENTE', 'EN_PROGRESO', 'COMPLETADA', name='estadometaenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.Enum('PLANIFICADA', 'PENDIENTE', 'EN_PROGRESO', 'COMPLETADA', name='estadometaenum'),
               type_=mysql.ENUM('PLANIFICADA', 'EN_EJECUCION', 'CUMPLIDA', 'CANCELADA'),
               existing_nullable=False)

    # ### end Alembic commands ###
