"""Add ip_origen to Auditoria model

Revision ID: e78ef3ff94f8
Revises: 22cbe827aa20
Create Date: 2025-05-28 01:51:00.969144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78ef3ff94f8'
down_revision = '22cbe827aa20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_origen', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_column('ip_origen')

    # ### end Alembic commands ###
